Support "new" Bitpanda Pro CSV export format
provinzio/CoinTaxman pull request #80
Opened 2021-10-17 20:24 UTC by uvok

Bitpanda added a "BEST_EUR rate" column.

This PR handles the new format. - In a way so that the old format is still supported. It also moves date parsing into the misc module.

This solves #79

2021-10-31 15:19 UTC, provinzio requested changes

2021-10-31 15:19 UTC, provinzio commented on src/book.py
> +            ] or line == [
I'd prefer the assert line in [xxx, xxx] variant.

2021-11-01 16:06 UTC, uvok commented on src/book.py
> +            ] or line == [
Okay, I changed it to that.

2021-11-02 08:52 UTC, provinzio approved these changes

2021-11-02 08:52 UTC, merged